name: 'tuva_claims_demo'
version: '0.1.0'
config-version: 2

profile: tuva_claims_demo                 # Configuration required (your profile to connect dbt to your data warehouse)


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  # These variables tell the_tuva_project package what
  # packages to run. If there are some packages you
  # are not interested in running, this is where you
  # need to set the relevant variable(s) to 'false':
  tuva_packages_enabled: true
  data_profiling_enabled: true
  claims_preprocessing_enabled: true
  chronic_conditions_enabled: true
  readmissions_enabled: true
  terminology_enabled: true

  # This variable sets the name of the database
  # where the output of the Tuva Project will be
  # dumped into. Make sure this database exists
  # in your data warehouse before you run this package,
  # since dbt can create schemas in your data warehouse,
  # but it cannot create databases.
  tuva_database: tuva_claims_demo_sample

  # This variable allows you to override the sample data seeds and
  # use the full demo data instead, you may also want to update the
  # tuva_database variable to not overwrite the sample demo
  full_data_override: false

# By default, dbt prefixes schema names with the target
# schema in your profile. We recommend including this
# here so that dbt does not prefix the output schemas
# of the Tuva Project with anything:
dispatch:
  - macro_namespace: dbt
    search_order: [ 'the_tuva_project', 'dbt' ]
